### ISSUE TITLE
Running on Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by dean-schulze** [rasbt/python-machine-learning-book-2nd-edition#111]
Running ch02.py 

` python3 ch02.py`

Gives this error:

$ python3 ch02.py
\Traceback (most recent call last):
  File "ch02.py", line 5, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.5/dist-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from .array_ import array  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/arrays/array_.py", line 7, in <module>
    from pandas.core.dtypes.common import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/common.py", line 11, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/dtypes.py", line 53, in <module>
    class Registry:
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/dtypes.py", line 84, in Registry
    self, dtype: Union[Type[ExtensionDtype], str]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

**Comment by rasbt** [comment]
Hm, that's weird -- never seen this before. Looks like a pandas import error. Maybe it's because of Python 3.5

I would recommend try a few things:

1. Create a new python script, lilke `test.py` containing only the line

```python
import pandas as pd
```

and then call it via

    python3 test.py

to see if you get a similar error.

2. If you get the same error, maybe try updating pandas.

3. If this doesn't resolve the problem, update your python version (from 3.5 to 3.6 or 3.7) to see if that solves the problem

**Comment by dwschulze** [comment]
It looks like my Python3 / pip / pip3 installation is corrupted.  I tried  it on a Ubuntu 18.04 distro and had no problems.  Closing this.

**Comment by rasbt** [comment]
Glad to hear that you found the issue and it wasn't due to a more serious issue.
