### ISSUE TITLE
Ch09 pythonanywhere.com web app error

### ISSUE THREAD

**Issue by markolonius** [rasbt/python-machine-learning-book-2nd-edition#61]
After following chapter 09 deploying to [pythonanywhere.com](url) I'm encountering an interesting error when providing feedback after clicking 'correct' or 'incorrect' button.  I have followed the book exactly to set up on [pythonanywhere.com](url)

Instructions to reproduce:
1. Go to [markolonius.pythonanywhere.com](url) and type a review and submit
2. Click correct or incorrect or 
3. Receive error:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

From error log:
```
2018-02-16 02:42:02,532: [2018-02-16 02:42:02,528] ERROR in app: Exception on /thanks [POST]
2018-02-16 02:42:02,532: Traceback (most recent call last):
2018-02-16 02:42:02,532:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
2018-02-16 02:42:02,532:     response = self.full_dispatch_request()
2018-02-16 02:42:02,533:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
2018-02-16 02:42:02,533:     rv = self.handle_user_exception(e)
2018-02-16 02:42:02,533:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
2018-02-16 02:42:02,533:     reraise(exc_type, exc_value, tb)
2018-02-16 02:42:02,533:   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
2018-02-16 02:42:02,533:     raise value
2018-02-16 02:42:02,533:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
2018-02-16 02:42:02,534:     rv = self.dispatch_request()
2018-02-16 02:42:02,534:   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
2018-02-16 02:42:02,534:     return self.view_functions[rule.endpoint](**req.view_args)
2018-02-16 02:42:02,534:   File "/home/markolonius/movieclassifier/app.py", line 72, in feedback
2018-02-16 02:42:02,534:     train(review, y)
2018-02-16 02:42:02,534:   File "/home/markolonius/movieclassifier/app.py", line 29, in train
2018-02-16 02:42:02,534:     clf.partial_fit(X, [y])
2018-02-16 02:42:02,535:   File "/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/stochastic_gradient.py", line 512, in partial_fit
2018-02-16 02:42:02,535:     coef_init=None, intercept_init=None)
2018-02-16 02:42:02,535:   File "/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/stochastic_gradient.py", line 348, in _partial_fit
2018-02-16 02:42:02,535:     self._validate_params()
2018-02-16 02:42:02,535:   File "/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/stochastic_gradient.py", line 95, in _validate_params
2018-02-16 02:42:02,535:     if self.n_iter <= 0:
2018-02-16 02:42:02,536: TypeError: unorderable types: NoneType() <= int()
```

Error log: [https://www.pythonanywhere.com/user/markolonius/files/var/log/markolonius.pythonanywhere.com.error.log](url)

**Comment by rasbt** [comment]
Hm, this is weird! Maybe something is not returning a value properly (I am guessing because of the NoneType). Does it work locally on your computer when you run it?

**Comment by markolonius** [comment]
Yep! Works perfect on my local computer when I run it.

**Comment by rasbt** [comment]
Hm, maybe that was a bad coincidence and the server was indeed overloaded at that time. But hey, it seems to work now :). 

![screen shot 2018-02-17 at 3 54 23 pm](https://user-images.githubusercontent.com/5618407/36345559-f073fff8-13fa-11e8-81d8-1ce31ff9efe2.png)

I am closing this issue now, but let me know if you have any questions!
